#
#
## 基本設定を記載したファイル。
##
## 設定の優先順位判定は、シリアル番号＞キャラ名（スタイル）＞キャラ名＞デフォルト の優先順位となる
#





############## 基礎情報

info:
  ## このYAMLファイルの構造仕様のバージョン
  ## 古い仕様のYAMLファイルを読み込まないようにする
  ver: "2.3.1"
  
  # ファイルの入出力先を指定する
  filedir:
    # 音声データのあるディレクトリ
    voidir: "./infile"
    # 動画の出力ディレクトリ
    outdir: "./outfile"
    # 立ち絵画像から動画の画面サイズの画像を生成した場合の保存場所
    # 生成を行わない場合も指定してください。
    out_picdir: "./public"
  # ファイル名の区切り文字として「-」を使うかどうか指定。
  kugirihaihun: "yes"




###################デフォルトの設定
#### 各キャラ・番号で指定のない場合はこの項目の値が適応される。

defo:
  df1:
    ####### 立ち絵
    # 立ち絵
    tatie: "./public/tatie_bc.png"
    # 「tatie」で指定した立ち絵画像を、そのまま画面の大きさにするかどうか。
    # すでに生成したい動画と同じサイズの画像を生成して指定している場合はyesを入れる。
    conp_tatie: "no"
    # 画面の横幅
    movi_w: "1280"
    # 画面の高さ
    movi_h: "720"
    # 立ち絵をどこに配置するかを指定します。
    tatie_muki: "SouthEast"
    # 立ち絵を画面の高さの何％にするか指定する。
    tatie_h_p: "50"
    # 入力される立ち絵と、出力される動画のフレームレート指定
    fps: "5"
    
    ######### 字幕
    # 字幕を表示するか指定（yesを入れると表示）
    enatext: "yes"
    # 字幕をどちらによせるか（L=左揃え,R=右揃え,それ以外=中央揃え）
    ena_muki: "tyuuou"
    # 字幕が画面横にはみ出してしまう場合、自動で改行を行うか指定（yesなら自動改行を行う）
    ena_auto_kaigyou: "yes"
    # 字幕のフチに色をつけるか指定定（yesを入れると表示）
    enatextbord: "yes"
    # 字幕の背景色をつけるか指定定（yesを入れると表示）
    enabg: "no"
    # デフォルトのフォントファイル
    voice_text_fonts: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
    # フォントサイズ
    voice_text_size: "38"
    # 字幕の背景色をつけない時の、文字下の空きスペースのサイズ（ピクセル単位）
    voice_text_u_space_size: "10"
    # フォントカラー
    voice_text_color: "0xFFFFFF"
    # フォント周りのフチの色
    voice_text_bordercr: "#000000"
    # フォント周りのフチの大きさ
    voice_text_borderw: "2"
    # 字幕の背景の色
    voice_text_bgcolor: "0x0000FF"
    # 字幕の背景の透明度
    voice_text_bgtoumei: "0.7"



##################################### 各キャラの設定 ####################################
##############デフォルトの項目から違う設定を行いたい場合はこちらに設定する。
##############こちらの設定が優先される

## 該当キャラの名前のみ指定（全スタイルに適応される）
## 次の、スタイルを指定したキャラ名の項目に該当がなければこちらが使用される。
kyara:
  ## 該当キャラの名前
  ＜キャラ名＞:
    ######### 字幕
    # フォントカラー
    voice_text_color: "0xFFFFFF"
    # フォント周りのフチの色
    voice_text_bordercr: "#FF69B4"
    # フォント周りのフチの大きさ
    voice_text_borderw: "1"



## キャラ名とスタイルの指定
## 前項のキャラ名のみの指定で同じ項目がある場合、こちらの設定が優先される。
kyara_st:
  ＜キャラクター名＞（スタイル）:
    ######### 字幕
    # フォントカラー
    voice_text_color: "0xFFFFFF"
    # フォント周りのフチの色
    voice_text_bordercr: "#00FF00"
    # フォント周りのフチの大きさ
    voice_text_borderw: "1"





##################################### シリアル番号の設定 ####################################
##############デフォルトの項目から違う設定を行いたい場合はこちらに設定する。
##############こちらの設定が最も優先される


seid:
  "9999_99":
    # フォントサイズ
    voice_text_size: "45"
    # フォント周りのフチの大きさ
    voice_text_borderw: "3"




