#
#
## 基本設定を記載したファイル。
##
## 設定の優先順位判定は、シリアル番号＞キャラ名（スタイル）＞キャラ名＞デフォルト の優先順位となる
#





############## 基礎情報

info:
  ## このYAMLファイルの構造仕様のバージョン
  ## 古い仕様のYAMLファイルを読み込まないようにする
  ver: "2.2.0"
  
  # ファイルの入出力先を指定する
  filedir:
    # 音声データのあるディレクトリ
    voidir: "./infile"
    # 動画の出力ディレクトリ
    outdir: "./outfile"
  # ファイル名の区切り文字として「-」を使うかどうか指定。
  kugirihaihun: "yes"




###################デフォルトの設定
#### 各キャラ・番号で指定のない場合はこの項目の値が適応される。

defo:
  ####### 立ち絵
  # 立ち絵
  tatie: "./public/base_1280x640.png"
  # 立ち絵が左右どちらにあるか（L=左,R=右,それ以外=中央揃え）
  muki: "tyuuou"
  # 入力される立ち絵と、出力される動画のフレームレート指定
  fps: "5"
  
  ######### 字幕
  # 字幕を表示するか指定（yesを入れると表示）
  enatext: "yes"
  # 字幕のフチに色をつけるか指定定（yesを入れると表示）
  enatextbord: "yes"
  # 字幕の背景色をつけるか指定定（yesを入れると表示）
  enabg: "no"
  # デフォルトのフォントファイル
  voice_text_fonts: "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
  # フォントサイズ
  voice_text_size: "38"
  # フォントカラー
  voice_text_color: "0xFFFFFF"
  # フォント周りのフチの色
  voice_text_bordercr: "#000000"
  # フォント周りのフチの大きさ
  voice_text_borderw: "2"
  # 字幕の背景の色
  voice_text_bgcolor: "0x0000FF"
  # 字幕の背景の透明度
  voice_text_bgtoumei: "0.7"



##################################### 各キャラの設定 ####################################
##############デフォルトの項目から違う設定を行いたい場合はこちらに設定する。
##############こちらの設定が優先される

kyara:
  ## 該当キャラの名前
  ＜キャラ名＞:
    ######### 字幕
    # フォントカラー
    voice_text_color: "0xFFFFFF"
    # フォント周りのフチの色
    voice_text_bordercr: "#FF69B4"
    # フォント周りのフチの大きさ
    voice_text_borderw: "1"
  ＜キャラクター名＞（スタイル）:
    ######### 字幕
    # フォントカラー
    voice_text_color: "0xFFFFFF"
    # フォント周りのフチの色
    voice_text_bordercr: "#00FF00"
    # フォント周りのフチの大きさ
    voice_text_borderw: "1"





##################################### シリアル番号の設定 ####################################
##############デフォルトの項目から違う設定を行いたい場合はこちらに設定する。
##############こちらの設定が最も優先される


seid:
  "999999":
    # フォントサイズ
    voice_text_size: "45"
    # フォント周りのフチの大きさ
    voice_text_borderw: "3"




